### ISSUE TITLE
Feature: add GUI to update bitcoin fun/ custom tracking

### ISSUE THREAD

**Issue by zooooooooo** [janoside/btc-rpc-explorer#122]
Got an idea for added tracking options, let me know what you think

How about if you put the bitcoin fun data in a JSON file, link the current spot to that file, add a plus button somewhere on address/tx/block pages that summons a bootstrap modal where you can enter the parameters of the bitcoin fun object, then on submitting your route appends the new data to the JSON file?

**Comment by janoside** [comment]
Thanks for the idea. However, for simplicity's sake I like the manual-update technique because it avoids needing to implement any UI for modifying the content. If you have some ideas for interesting things to highlight please feel free to submit a PR. FYI, the content is here:

https://github.com/janoside/btc-rpc-explorer/blob/master/app/coins/btc.js#L108
