### ISSUE TITLE
Address showing zero balance/history

### ISSUE THREAD

**Issue by sangaman** [janoside/btc-rpc-explorer#129]
I'm getting no balance or history for an address that definitely does has some, `13TETb2WMr58mexBaNq1jmXV1J7Abk2tE2`. Pulling up a transaction that had an output to this address does work and it shows that this address received bitcoin, but clicking through to the address shows nothing. Restarting does not resolve the issue.

I clipped this from the logs, I'm not sure why it's fetching `RETgK5aCu6w3LppdAxg6ETmI65AcuOzL` and if this is some strange cache issue.

```
  express:router dispatching GET /address/13TETb2WMr58mexBaNq1jmXV1J7Abk2tE2 +33
s
  express:router query  : /address/13TETb2WMr58mexBaNq1jmXV1J7Abk2tE2 +1ms
  express:router expressInit  : /address/13TETb2WMr58mexBaNq1jmXV1J7Abk2tE2 +1ms
  express:router jsonParser  : /address/13TETb2WMr58mexBaNq1jmXV1J7Abk2tE2 +0ms
  body-parser:json skip empty body +1ms
  express:router urlencodedParser  : /address/13TETb2WMr58mexBaNq1jmXV1J7Abk2tE2
 +0ms
  body-parser:urlencoded skip empty body +0ms
  express:router cookieParser  : /address/13TETb2WMr58mexBaNq1jmXV1J7Abk2tE2 +0m
s
  express:router session  : /address/13TETb2WMr58mexBaNq1jmXV1J7Abk2tE2 +1ms
  express-session fetching RETgK5aCu6w3LppdAxg6ETmI65AcuOzL +1ms
  express-session session found +1ms
  express:router serveStatic  : /address
```

The electrs logs show requests coming in with a scripthash that does not match the scripthash for address `13TETb2WMr58mexBaNq1jmXV1J7Abk2tE2`.

```
TRACE - RPC Request("{\"jsonrpc\":\"2.0\",\"method\":\"blockchain.scripthash.get
_history\",\"params\":[\"bce4d5f2803bd1ed7c1ba00dcb3edffcbba50524af7c879d6bb918d
04f138965\"],\"id\":22}\n")
TRACE - RPC Request("{\"jsonrpc\":\"2.0\",\"method\":\"blockchain.scripthash.get
_balance\",\"params\":[\"bce4d5f2803bd1ed7c1ba00dcb3edffcbba50524af7c879d6bb918d
04f138965\"],\"id\":23}\n")
```

The issue here is similar to #76 but it seems to have a different cause based on the logs and it's only happening for this one address. Chaintools does not have a problem with this address.

**Environment:**
 - bitcoind 0.18.0
 - node 10.15.3
 - Firefox
 - Commit 256b4650c9b1283418a0652ac3f65e6a299b22a4

**Comment by janoside** [comment]
@sangaman I'm trying to cleanup old issues. Taking a look here, I think there must be some bug with electrs and/or electrumX. Looking up address `13TETb2WMr58mexBaNq1jmXV1J7Abk2tE2` in electrs-based address apis (my public demo site https://explorer.btc21.org, https://blockstream.info, and https://mempool.space) all return no transactions for the address. But non-electrs-based tools (at least I believe these to use a different address-lookup implementation: https://blockchain.com and https://blockchair.com) show 2 tranactions.

I couldn't venture a guess about the reason for this, but it does seem to be a bug there, rather than in this tool directly.

I'm closing this for now, but happy to investigate if you have any other info that changes the idea here.

**Comment by shesek** [comment]
It's because blockchain.com and blockchair.com (and some other explorers) represent P2PK scripts using the P2PKH base58 address encoding, which is wrong. P2PK script don't have an address representation.

They can, however, be represented as a scripthash and queried using both the Electrum RPC `blockchain.scripthash.*` methods and via `blockstream.info/api/scripthash/<hash>`.

This is the relevant funding transaction on blockchair, showing the wrong address: https://blockchair.com/bitcoin/transaction/cca7507897abc89628f450e8b1e0c6fca4ec3f7b34cccf55f3f531c659ff4d79

And here it is on blockstream.info, showing as "P2PK": https://blockstream.info/tx/cca7507897abc89628f450e8b1e0c6fca4ec3f7b34cccf55f3f531c659ff4d79?output:1

Also see:
- https://twitter.com/adam3us/status/1087013943330172930
- https://twitter.com/murchandamus/status/1263171240128155648

**Comment by janoside** [comment]
@shesek Awesome, thanks for the education on the matter!
