### ISSUE TITLE
Reconnecting to electrum server

### ISSUE THREAD

**Issue by sangaman** [janoside/btc-rpc-explorer#131]
I'm using btc-rpc-explorer with electrs. If I stop and restart electrs, it seems that btc-rpc-explorer can't communicate with it until I stop and restart btc-rpc-explorer as well. It would be nice to be able to reestablish communication with the electrum server automatically. Not sure if this also happens with electrumx or public electrum servers.

**Comment by schildbach** [comment]
I also happens with electrumx. This makes it pretty hard to automatically start up btc-rpc-explorer correctly, since the waiting time for electrumx can vary wildly (from a couple of seconds to days).

Also, I assume if it would loose its connection it wouldn't reconnect either.

**Comment by 3ntranced** [comment]
I think it also happens if bitcoind is restarted. Then btc-rpc-explorer also needs to be restarted before it can reconnect.

**Comment by janoside** [comment]
@sangaman After recent changes to the electrum connection I believe this issue is resolved - at least the tool successfully reconnects in my testing (after ElectrumX is brought down and then back up shortly after...I'm unsure about long downtimes). This is not yet included in an official release, so I'm leaving this issue open, but if you run the latest code I believe it's resolved.

**Comment by janoside** [comment]
Fixed in v2.0.2.
