### ISSUE TITLE
Is txindex required when used with Electrum?

### ISSUE THREAD

**Issue by lukechilds** [janoside/btc-rpc-explorer#155]
It would be great if we already have an Electrum server in front of our bitcoind instance to query Electrum for transactions and not require txindex on bitcoind.

This would reduce load on bitcoind and also reduce storage requirements.

Is this currently possible? If not, would it take much work to implement?

**Comment by janoside** [comment]
This is not currently possible. I'd guess the work to implement would be in the medium range.

The founding principle of the project was to be a frontend specifically for bitcoind, so using bitcoind for everything possible was and still is the design goal. I like ElectrumX and am happy to support using it for things that bitcoind *can't* do, but don't think it's wise to go against this guiding principle at this point.

I'm also worried that optionally implementing this via a feature flag ("if ElectrumX available, pull transaction data from there, otherwise use bitcoind") would be a bit messy in terms of the code.

So yea...sorry that I'm not super keen on this, but I grant you it's an interesting idea. I'm not so against it as to reject it outright; I'm open to reviewing a PR that attempts this, but no promises about merging if it does end up being messy or confusing to the average user.
