### ISSUE TITLE
Cosmetic: Fee rate listed with mixed braces

### ISSUE THREAD

**Issue by frennkie** [janoside/btc-rpc-explorer#176]
The **Fee Rate** steps are listed like this:
* [0 - 1)
* [1 - 2)
* ...

Why are two different types of braces (**[** vs. **)**) used? Is this done on purpose or is it just a typo?

Fix would go here:

https://github.com/janoside/btc-rpc-explorer/blob/ff4dea980d4b4f640e9553fe1f455449a1d69742/app/api/coreApi.js#L452

**Comment by janoside** [comment]
Hi @frennkie - I agree it can look a little weird, but yes, this is intentional. It's mimicking mathematical notation for ranges, in which a square brace means "including the value on this end of the range" and a rounded-brace or parenthesis means "excluding the value on this end of the range". Thanks for checking.
