### ISSUE TITLE
npm start is being killed randomly

### ISSUE THREAD

**Issue by dgsqrs** [janoside/btc-rpc-explorer#196]
Hi,

I'm starting btc-rpc-explorer using npm start &
The app is being killed randomly. I don't know where to see the log (/var/log/syslog does not contain anything related)

Is there another way to start the app ?

**Comment by janoside** [comment]
In my experience running `npm start` will output logs right into the commandline where you ran that command - I'm surprised you're not seeing any logs output there. How exactly are you executing the `npm start` command - are you "backgrounding" the command, like `npm start &`?

For reference, I do primarily use `npm start` when running locally, so I'm surprised that it's crashing for you. Perhaps your system is using different default memory settings than mine.

Another way to run, that will allow you to set a different memory threshold is:

    node --max_old_space_size=3000 bin/www

In that example the `3000` is a value in MB.

**Comment by dgsqrs** [comment]
Yes I'm backgrounding the app using `npm start &`
What is the recommended way to run the app on a server ?

**Comment by janoside** [comment]
Ah, ok...

I use the npm package `pm2` to run on servers. That tool will will output logs to something like `~/.pm2/logs` and will restart the app if it crashes.

To run with `pm2` I basically do the following (this is from [Server-Setup.md](https://github.com/janoside/btc-rpc-explorer/blob/master/docs/Server-Setup.md)):

    npm install pm2 --global
    cd /dir/with/btc-rpc-explorer
    pm2 start bin/www --name "btc-rpc-explorer"

That will register the app with `pm2`. Then in the future you can restart like:

    pm2 restart btc-rpc-explorer

And just FYI for future reference, I'm suspecting now that your crashes might be due to "hang-up" signals being sent because of how you're starting up. (I learned this recently when running `lnd` on a server.) If you want to start up from the terminal on your server and background it as a daemon, you should also prefix your command like this:

    nohup npm start &

The leading `nohup` is a server utility that will prevent crashes due to hang-up signals. And, one more thing: if you do decide to run this way (I still recommend `pm2` but you could do this as a trial), you should be able to see your logs if you add a little more to your command, like this:

    nohup npm start > out.log &

That will redirect stdout output from the `npm start` command to a log file `out.log`.

Hope this all helps. Let me know.

**Comment by dgsqrs** [comment]
I can affirm that I have no more problem using pm2, thanks a lot
