### ISSUE TITLE
show total money supply

### ISSUE THREAD

**Issue by MaxHillebrand** [janoside/btc-rpc-explorer#216]
### Show total issued money supply

In the `Network Summary` under `Financials`, show the total supply of bitcoin which have already been issued at the current block tip. It's kinda the core feature of verification :wink: 

I believe this can be fetched with `gettxoutsetinfo` and `total_amount`. Notice that this amount will exclude unspendable coins like OP_RETURN, afaik.

**Comment by janoside** [comment]
Hey @MaxHillebrand - we actually already have this feature! Since it involves pulling the utxo set summary, which is a resource-intensive task, it's disabled by default. But, you can easily turn it on with either the environment variable:

    BTCEXP_SLOW_DEVICE_MODE=false

or CLI arg (note that the CLI arg had a bug so didn't work before v2.0.1):

    --slow-device-mode=false

After you do that, you'll be able to see the total supply in the "Network Summary" on the homepage:

<img width="1139" alt="Screen Shot 2020-05-30 at 10 52 31 AM" src="https://user-images.githubusercontent.com/99734/83331374-7f669200-a285-11ea-89a4-3902df5c0efe.png">

Hovering the value will also show the fraction of the total supply that value represents (taking [some known coin losses](https://bitcoin.stackexchange.com/a/38998) into account)
