### ISSUE TITLE
Multicoin options/information/help

### ISSUE THREAD

**Issue by pouyiouk** [janoside/btc-rpc-explorer#248]
Hello guys, I was wondering how I can configure the explorer in order to allow the option to load Bitcoin Cash, and Bitcoin SV chains alongside Bitcoin, since I am running all three nodes on the same machine. Can anyone assist me in linking the other two as well? 

 Also, is there any work in the pipeline for future functionality for allowing connection to geth via web3 for Ethereum?

**Comment by janoside** [comment]
Hi @pouyiouk - I'm happy if you find this project useful in any capacity, but I explicitly don't support any coins except BTC. If you want to support any other coin, you can start by referring to the old file `app/coins/ltc.js` (from when I used to support LTC), but there are likely many things that have broken since I dropped LTC support.

**Comment by pouyiouk** [comment]
Thank you for the insights @janoside . I will try and use the explorer for the forks of BTC and come back with the results. Since I am running the nodes on a testbed I guess rerunning separate instances of the explorer making use of the different ports and directing the explorer to different ports in the localhost would theoretically work.
