### ISSUE TITLE
XSS in TX, Address request

### ISSUE THREAD

**Issue by 2HelpInfo** [janoside/btc-rpc-explorer#256]
**Describe the bug**

XSS in TX, Address request

![Screenshot 2020-12-05 at 12 10 30](https://user-images.githubusercontent.com/75522564/101238711-10b23780-36f3-11eb-92bb-325b71f1d05c.png)

**Environment (please complete the following information):**

 - Bitcoin Core / Node Version ?
 - NodeJS Version ?
 - Browser ?
 - Code Version / Commit ?
 
**To Reproduce**

1. Go to https://explorer.btc21.org/tx/ or https://explorer.btc21.org/address/
2. Put XSS Payload `;'"1<Svg OnLoad=(alert)(1)>/`
3. See error 
https://explorer.btc21.org/tx/;'%221%3CSvg%20OnLoad=(alert)(1)%3E/
https://explorer.btc21.org/address/;'%221%3CSvg%20OnLoad=(alert)(1)%3E/

If you see alert(1), there is an XSS.

**Comment by Kixunil** [comment]
I think it'd be better to report vulnerabilities like this one privately. I already know of ways how this can be actually weaponized. Thank God I restricted the access to `btc-rpc-explorer` in my repository.

**Comment by shesek** [comment]
It seems like the cause is that unsanitized user input is used as part of a markdown string (`userMessageMarkdown`), which is later rendered to html with [`marked`](https://github.com/markedjs/marked), which lets HTML pass through without sanitizing it.

I would suggest to replace `marked` with [`markdown-it`](https://github.com/markdown-it/markdown-it), which by default prevents HTML from passing through, and also to sanitize the user input when it is read but using a specialized sanitization for the expected data formats instead of using the `sanitizer` dependency introduced by https://github.com/mjmacleod/nlg-rpc-explorer/commit/db4a78fb7dd5a55c530d61b24027077d6cc8ae46.

If this approach sounds right, I can submit a PR for this.

**Comment by janoside** [comment]
I haven't investigated myself yet, but this sounds like a good approach.

**Comment by 2HelpInfo** [comment]
I tried using string-sanitizer and it seems like a good solution.
