### ISSUE TITLE
Official logo?

### ISSUE THREAD

**Issue by Kixunil** [janoside/btc-rpc-explorer#269]
I'd like `btc-rpc-explorer` to have some official logo so that it can be easily distinguished from other applications. I may be able to get someone skilled in graphics to make it. Was thinking about Bitcoin logo with magnifying glass as a simple idea but may be something else too.

What do you think? Would be great if it was approved by the author. :)

**Comment by janoside** [comment]
@Kixunil Thanks for the suggestion - I like the idea of an official logo and I think others will appreciate that too, as it gets integrated into more products.

I'm open to your contact taking a stab at making one, though I admit that I tend to have strong opinions so not sure I'll go for it. But, since what's there now is so mundane, as long as a new one isn't awful or weird in some way it'll probably be an improvement!

I may brainstorm too.

**Comment by janoside** [comment]
The v3 branch introduces a custom logo for the project and will be merged soon, so I'm closing this.

I'm happy to hear any feedback on the logo - it's intentionally simple/subtle while trying to integrate the mapping/location/searching concept with bitcoin.

Thanks for the inspiration!

**Comment by Kixunil** [comment]
Awesome! Having something certainly helps. Even though I would personally prefer something more obvious, I respect your choice. Any (rough) plans on release date?

**Comment by janoside** [comment]
Shooting for early next week release.
