### ISSUE TITLE
txindex=1 question

### ISSUE THREAD

**Issue by kalibox** [janoside/btc-rpc-explorer#304]
**Describe the bug**

txindex=1 configured in bitcoin.conf but txindex under the node details page shows an X mark against it.

**Environment (please complete the following information):**

 - Bitcoin Core / Node Version [e.g. 0.16.3] - v0.21.0
 - NodeJS Version [e.g. 9.x] - NA
 - Browser [e.g. chrome, safari] - Brave, Chrome
 - Code Version / Commit [e.g. ab6cde8] - v3.0.0

Command used to launch the explorer:

btc-rpc-explorer -i 0.0.0.0 -p 4747 -H 1xx.xx.1xx.xx5 -P 8332 -u <aaa> -w <pwd> --address-api=blockcypher.com
 
Thoughts please?

**Comment by kalibox** [comment]
Also, thank you for this brilliant tool. I have donated in the past and will certainly do so again for giving us v3.0.0. :)

**Comment by janoside** [comment]
@kalibox You're running into a known bug related to identification of `txindex` availability in v3.0.0. A fix has already been pushed to the repository, but there's no official release that includes it yet (working toward v3.1.0 pretty soon). Since the fix is already in, I'm closing this, but thanks for reporting.

Also thank you very much for your donation/support - it's much appreciated!

**Comment by kalibox** [comment]
Hey @janoside, apologies I didn't take a peek at the closed issues to realise this a known bug. Thanks for looking and replying though. Much appreciated.

**Comment by kalibox** [comment]
May I also suggest putting up a persistent LN invoice alongside your BTC address; fees are much bearable in the lightning world :)
