### ISSUE TITLE
question about the balance of the address

### ISSUE THREAD

**Issue by serogaF** [janoside/btc-rpc-explorer#347]
hello everyone, first I want to thank you for the project, I launched the explorer and I want to find out the balance on the address, but in the transaction field I see: No address API is configured., and there is no Summary field at all, please tell me what else I need to do or enable , so that I could request the balance at any address, thanks in advance

**Comment by janoside** [comment]
@serogaF You're welcome!

Concerning the address API: you have a few options. If you look at the example config file [here](https://github.com/janoside/btc-rpc-explorer/blob/master/.env-sample#L48) you can see the options for address APIs that are available. The first 2: "electrum" and "electrumx" are actually identical under the hood and indicate that, if you wish, you can run another piece of software that implements the "electrum protocol". My top recommendation for an electrum server is [electrs](https://github.com/romanz/electrs). If you choose this option, you will have the most privacy possible since you'll be querying your own address database. But it will also require some technical work to get it set up, and some disk space to store the database. If you want a less technical option you can use any of the last 3 address APIs: "blockchain.com", "blockchair.com", or "blockcypher.com". If you use any of these options, the explorer tool will call out to the public API for the respective option to get details about addresses. Please note: In doing so, it will be possible for those companies to log your IP address and correlate it with the addresses that you're interested in, potentially seriously damaging your privacy.
