### ISSUE TITLE
Cannot view transaction history of Address

### ISSUE THREAD

**Issue by odomdev** [janoside/btc-rpc-explorer#353]
Failed to retrieve transaction history from ElectrumX because this address is involved in too many transactions (more than ElectrumX currently supports retrieving). See Issue #67 for more information.

**Comment by odomdev** [comment]
Hi Admin any update ?

**Comment by janoside** [comment]
This issue is actually a problem with the electrum dependency. I'll continue to monitor the situation but no specific fixes are possible at this time.

FYI, if you run [electrs](https://github.com/romanz/electrs), I believe you can configure that server to offer responses for larger-history addresses (using the `--txid-limit` setting). That's something you may consider investigating.
