### ISSUE TITLE
BTC pricing data via RPC Explorer API URL

### ISSUE THREAD

**Issue by BTCfan86** [janoside/btc-rpc-explorer#409]
Hello,

I have been trying to access bitcoin pricing and market cap data through Umbrel’s BTC RPC Explorer app. However, when I go to the URLs for the endpoints shown on the app’s API page (such as IP/port/api/price), the returned data is either a null value or zero. I have been able to access block and txid data through these APIs without a problem, so I know other APIs work with this app on my node. Is there another term I should include in my API calls to retrieve bitcoin pricing and market cap data?  This is for a local node I'm running using Umbrel's RPC explorer app on a Raspberry Pi4.  I appreciate any help. Thanks.

**Comment by janoside** [comment]
@BTCfan86 I believe that Umbrel ships with btc-rpc-explorer's privacy settings enabled by default. One of those settings is to disable external API requests, which is how the explorer gets its price data - that's why the explorer can't return it via the API. I'm proud that the explorer supports this hardcore-ish privacy option, but I think it's probably overkill to enable it by default on a consumer-oriented product like Umbrel, and I think doing so does diminish the explorer's appeal on that platform. However, this decision was made by the Umbrel team, so I suppose you could make a request there. But they seem to have bigger fish to fry building out their platform.
